### ISSUE TITLE
Status per mandag 19. september 2015

### ISSUE THREAD

**Issue by batfink** [askoyfk/askoyfk.github.io#39]
* [ ] Oppdatere DNS
* [ ] Oppdatere kontaktliste #13
* [ ] Legge inn sponsoravtaler #19
* [ ] Legge inn nye treningstider #36
* [ ] Arkiv fra gammel webside #37

**Comment by batfink** [comment]
Tenkte å gå gjennom listen på styremøtet i morgen. Jeg redigerer og legger til flere punkter innimellom når jeg har tid frem til da. Legg gjerne inn forslag.

**Comment by FrodeFjell** [comment]
Flott

 

Frode
 



Date: Mon, 19 Jan 2015 04:07:10 -0800
